FROM node:lts as builder
WORKDIR /frontend
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev"]

# FROM nginx:latest
# COPY --from=builder /frontend/build /usr/share/nginx/html
# CMD ["nginx", "-g", "daemon off;"]