FROM node:lts as builder
WORKDIR /frontend
COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build 


FROM nginx:stable-alpine

COPY --from=builder /frontend/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]